### ISSUE TITLE
Keep hashes for documents downloaded

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-scraper-addon#12]
Sometimes we have a site that updates daily, the file name is the same, but the contents of the file change daily. Here is one such site: https://www.alameda.courts.ca.gov/general-information/calendars
where the Calendar PDF gets updated daily, but with the same name. 

We should be able to handle this case. I am thinking of an approach like this:
For the event data for the scraper, for any URLs where we actually capture files from, we also include a list of file hashes. 

Each time we take a look at the URL, if the file hash of the current file isn't in the list of previously seen hashes, we add the file to the list of documents to be uploaded, and add the new hash to the list of hashes for that URL. This way, we can also keep track of files as they change on a site we scraped.

**Comment by mitchelljkotler** [comment]
You would have to download the entire file to take its hash, which we want to avoid doing.  You could do something similar to this using etags if the site supports them:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
