### ISSUE TITLE
Scraper can't see Google Drive links

### ISSUE THREAD

**Issue by eyeseast** [MuckRock/documentcloud-scraper-addon#3]
Since they're an HTML viewer, not a PDF file, they don't look like files we can store.

This page is full of them: https://www.bostonpublicschools.org/Page/9348

Here's a single link: https://drive.google.com/file/d/1m8lzx0DvZj_hebp5Yhalb0PsvlQOREW3/view?usp=drive_link

**Comment by duckduckgrayduck** [comment]
After adding the gdrive docs to site_data, having 500/403 issues, need to investigate more

**Comment by duckduckgrayduck** [comment]
Fixed with some error  handling.
